version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTRGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfiles/api/dev.Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_BACKENDS=django.db.backends.postgresql
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=db
      - DJANGO_DB_USERNAME=user
      - DJANGO_DB_PASSWORD=password
    ports:
      - "7777:7777"
    command: >
      python gen_secret_key.py && \
      python init_torch.py && \
      python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver 0:7777

    volumes:
      - ./api/:/app/
volumes:
  db-data:
  api-data:
